---

- name: "Check if cluster exists and the first node in hosts.ini exists in the status output"
  shell: "rabbitmqctl cluster_status | grep {{ hostvars.keys()[0] | replace('.' + dynect_env_domain, '') }}"
  register: cluster_result
  changed_when: False
  ignore_errors: True
  when: hostvars.keys()[0] != ansible_fqdn

- name: "stop rabbitmq app"
  shell: "rabbitmqctl stop_app"
  when: cluster_result is defined and cluster_result.rc == 1

# for this to work, an entry including the short hostname must exist in /etc/hosts
- name: "add this node to cluster"
  shell: "rabbitmqctl join_cluster rabbit@{{ hostvars.keys()[0] | replace('.' + dynect_env_domain, '') }}"
  when: cluster_result is defined and cluster_result.rc == 1

- name: "start rabbitmq app"
  shell: "rabbitmqctl start_app"
  when: cluster_result is defined and cluster_result.rc == 1

