---

- name: "look up dns names"
  shell: "python -c \"import socket; print socket.gethostbyname('{{ item }}')\""
  register: rabbitmq_servers
  changed_when: False
  with_items: groups['rabbitmq']

- name: "Ensure every rabbit server have entries about other rabbit servers in /etc/hosts (this task must be run on all servers in the rabbitmq group simultaneously to resolve facts)"
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^{{ item.stdout }}"
    line: "{{ item.stdout }}{{'\t'}}{{ item.item }}{{'\t'}}{{ item.item | replace('.' + dynect_env_domain, '') }}"
    state: present
  with_items: rabbitmq_servers.results
