---

- name: "look up dns names"
  shell: "python -c \"import socket; print socket.gethostbyname('{{ item }}')\""
  register: rabbitmq_servers
  with_items: groups['rabbitmq']

- name: "Ensure every rabbit server have entries about other rabbit servers in /etc/hosts (this task must be run on all servers in the rabbitmq group simultaneously to resolve facts)"
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^{{ item.stdout }}"
    line: "{{ item.stdout }}{{'\t'}}{{ item.item }}{{'\t'}}{{ item.item | replace('.' + dynect_env_domain, '') }}"
    state: present
  with_items: rabbitmq_servers.results

# This one has issues; hostvars variable is in an unknown state depending on execution flow of ansible!
#
# ansible behaves weirdly and removes information from the contents of the hostvars variable
# during execution. Depending on when you run this task it may work or give an error like:
# "One or more undefined variables: 'dict object' has no attribute 'ansible_fqdn'"
#
#- name: "Ensure every rabbit server have entries about other rabbit servers in /etc/hosts (this task must be run on all servers in the rabbitmq group simultaneously to resolve facts)"
#  lineinfile:
#    dest: "/etc/hosts"
#    regexp: "^{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
#    line: "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}{{'\t'}}{{ hostvars[item]['ansible_fqdn'] }}{{'\t'}}{{ hostvars[item]['ansible_hostname'] }}"
#    state: present
#  with_items: groups['rabbitmq']

# The following is a way to remove one line added by the task above.
# Is there an easier way to filter out own ip from groups['rabbitmq']?
- name: "ensure own ip address is not in the /etc/hosts file"
  lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ ansible_eth0.ipv4.address }}.*{{ ansible_fqdn }}.*"
    state: absent